<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-15T14:24:27+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyAZllF5XDvVVnes3LWrfAWBW7Q-vD7YAvY',
        ],
    ],
];
